services:
  db:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parmclick
      MYSQL_USER: routy
      MYSQL_PASSWORD: routy
    ports:
      - "3308:3306"
    volumes:
      - db_dataa:/var/lib/mysql

volumes:
  db_dataa: